#trigger:
#- master

pool:
  name: Openshift-agent-pool

steps:
- task: oc-cmd@2
  displayName: 'OC Status '
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OS-Dev-Test'
    cmd: 'oc status'

- task: oc-cmd@2
  displayName: 'Create Project dev-ado-aro'
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OS-Dev-Test'
    cmd: 'oc new-project dev-ado-aro --display-name dev-ado-aro'

- task: oc-cmd@2
  displayName: 'Select Project dev-ado-aro'
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OS-Dev-Test'
    cmd: 'oc project dev-ado-aro' 
        
- task: oc-cmd@2
  displayName: 'Deploy App from Git'
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OS-Dev-Test'
    cmd: 'oc new-app https://github.com/EnforcerRack/nodejs-ex -l name=ADO-ARO'
      
