# trigger:
# - master

pool:
  name: OpenShift-agent-pool-STG

stages:

  - stage: CI
    displayName: CI Stage
    jobs:
  
    - job: build
      displayName: build
  
      steps:
  
      - task: CopyFiles@2
        inputs:
          contents: '**'
          targetFolder: $(Build.ArtifactStagingDirectory)
  
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: artifact

# stages:
# - stage: CI
#   displayName: CI Stage
#   jobs:

#   - job: build
#     displayName: build
#     steps:

#     - task: CopyFiles@2
#       displayName: 'Copy manifest to staging area to be published'
#       inputs:
#         SourceFolder:
#         Contents: '**'
#         TargetFolder: '$(Pipeline.Workspace)'
#     - task: PublishBuildArtifacts@1
#       inputs:
#         PathtoPublish: '$(Pipeline.Workspace)'
#         ArtifactName: 'manifest'
#         publishLocation: 'Container'


  - stage: CD_DEV
    displayName: CD-DEV Stage
    jobs:
    - deployment: deploy
      displayName: Deployment
      environment: OpenShift-ADO-ARO-STG
      strategy:
        runOnce:
          deploy:
            steps:


            - task: oc-cmd@2
              displayName: 'OC Status '
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'OpenShift-ADO-ARO-STG'
                cmd: 'oc status'
      
            - task: oc-cmd@2
              displayName: 'Create Project dev-ado-aro'
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'OpenShift-ADO-ARO-STG'
                cmd: 'oc new-project dev-ado-aro --display-name dev-ado-aro'
      
            - task: oc-cmd@2
              displayName: 'Select Project dev-ado-aro'
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'OpenShift-ADO-ARO-STG'
                cmd: 'oc project dev-ado-aro' 
                  
            - task: oc-cmd@2
              displayName: 'Deploy App from Git'
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'OpenShift-ADO-ARO-STG'
                cmd: 'oc new-app $(Build.ArtifactStagingDirectory)/artifact -l name=ADO-ARO-DEV'

            - task: oc-cmd@2
              displayName: 'Expose nodejs-ex App'
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'OpenShift-ADO-ARO-STG'
                cmd: 'oc expose service/nodejs-ex'

# - stage: CD_PROD
#   displayName: CD-PROD Stage
#   jobs:
#   - deployment: deploy
#     displayName: Deployment in PROD
#     environment: OpenShift-ADO-ARO-STG
#     strategy:
#       runOnce:
#         deploy:
#           steps:
          
#           - task: oc-cmd@2
#             displayName: 'Deploy App from Git'
#             inputs:
#               connectionType: 'OpenShift Connection Service'
#               openshiftService: 'OpenShift-ADO-ARO-STG'
#               cmd: 'oc new-app https://github.com/EnforcerRack/nodejs-ex -l name=ADO-ARO-PROD'

#           - task: oc-cmd@2
#             displayName: 'Expose nodejs-ex App'
#             inputs:
#               connectionType: 'OpenShift Connection Service'
#               openshiftService: 'OpenShift-ADO-ARO-STG'
#               cmd: 'oc expose service/nodejs-ex'